### ISSUE TITLE
Update on components topic needed

### ISSUE THREAD

**Issue by AdityaSrivastava185** [AdityaSrivastava185/Reactjs-For-Beginners#24]
The documentation for Reactjs components needs updating to reflect the latest and best practices and features introduced in recent react versions , This includes adding examples , clarifying , prop usage and ensuring consistency across all components documentations

**Comment by ajay0180** [comment]
can you assign this issue to me?

**Comment by AdityaSrivastava185** [comment]
This issue is already assigned , I would like to request to to check out the rest of the issues to get assigned 
Thank you for considering , Looking forward to assign you the other issues @ajay0180 
Happy Contributing ✨
