### ISSUE TITLE
GitHub Beginner Documentation !!

### ISSUE THREAD

**Issue by yashksaini-coder** [AdityaSrivastava185/Reactjs-For-Beginners#27]
**Issue Title: Request for New Beginner's Guide Section in GitHub Documentation**
Many new users find GitHub's documentation overwhelming and challenging to navigate. The current documentation lacks a structured, beginner-friendly guide that introduces fundamental concepts and basic usage in a clear and accessible manner.

**Describe the solution you'd like**
I propose creating a new section in the GitHub documentation specifically designed for beginners. This section should include:-

1. **Introduction to GitHub**: Overview of what GitHub is and how it fits into the software development lifecycle.
2. **Getting Started**: Step-by-step instructions for setting up a GitHub account, creating a repository, and basic Git operations (clone, commit, push, pull).
3. **GitHub Interface**: Explanation of key features and components of the GitHub web interface, including repositories, issues, pull requests, and actions.
4. **Basic Workflow**: Simple workflows for common tasks like collaborating on projects, managing issues, and merging pull requests.
5. **Troubleshooting and FAQs**: Common problems beginners face and how to resolve them.

**New Section**
The Github Documentation will be stored in a new row in the Lesson table:
![image](https://github.com/user-attachments/assets/456194e4-a0f8-4a64-85bf-f718c8544b52)

This guide is supposed to be written straightforward & in easy to understand language and include visual aids such as screenshots or diagrams to enhance understanding.

**Comment by yashksaini-coder** [comment]
@AdityaSrivastava185 As per our agreement, Assign this issue to me.

**Comment by AdityaSrivastava185** [comment]
Hello @yashksaini-coder   , Assigned this issue to you , make sure to make changes only in this file [git-basics](https://github.com/AdityaSrivastava185/Reactjs-For-Beginners/tree/main/git-basics)

**Comment by yashksaini-coder** [comment]
@AdityaSrivastava185 got it 👍 will provide an update by tomorrow.

**Comment by yashksaini-coder** [comment]
Hi @AdityaSrivastava185 I forgot to ask do you want the documentation only in Markdown file or also include a basic React app too inside the [git-basics](https://github.com/AdityaSrivastava185/Reactjs-For-Beginners/tree/main/git-basics)

**Comment by AdityaSrivastava185** [comment]
For now keep the documentations based only but make in such a way that user can find it easy to uderstand and implment to learn

**Comment by yashksaini-coder** [comment]
> For now keep the documentations based only but make in such a way that user can find it easy to uderstand and implment to learn @yashksaini-coder

okh @AdityaSrivastava185  I will leave it on simple markdown format. It will be easy for others to create, edit, and understand the contents of the docs.  

2 files mainly:
- Git.md (for git commands & essentials features)
- GitHub.md (Consisting all the important essentials & steps on how to interact with this platform.)

**Comment by AdityaSrivastava185** [comment]
Please share your linkedin id
